### ISSUE TITLE
Cannot successfully run it

### ISSUE THREAD

**Issue by fengnex** [codecitizen/jlibvips#14]
VipsBindingsSingleton.configure("/usr/lib64/libvips.so");
The path of libvips.so is ok, but got the following error:

2019-05-21 18:29:42.600 ERROR 27932 --- [nio-8090-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for serv
let [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchM
ethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;] with root cause

java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;
        at org.jlibvips.jna.VipsBindingsSingleton.instance(VipsBindingsSingleton.java:21) ~[jlibvips-1.2.0.RELEASE.jar!/:1.2.0.
RELEASE]
        at org.jlibvips.VipsImage.fromFile(VipsImage.java:81) ~[jlibvips-1.2.0.RELEASE.jar!/:1.2.0.RELEASE]

**Comment by fengnex** [comment]
have fixed it, thx

**Comment by fengnex** [comment]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f0e437f19a9, pid=7126, tid=0x00007f0e49111700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libvips.so+0x5a9a9]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /opt/tst/hs_err_pid7126.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted

**Comment by codecitizen** [comment]
On which operation does the crash appear?
